### ISSUE TITLE
Character Count Not Updating Score.

### ISSUE THREAD

**Issue by AdamGaffney96** [cssbattle/forum#265]
I'm doing the One Piece battle from the most recent pack, and I submitted my code to make sure it was accurate before running through my usual size reduction checklist. My submitted high score gave a 100% match at 2834 characters. Upon running my reductions I've brought it down to 1323 characters, however the score is exactly the same (600) and the high score is taking my highest character count instead of the lowest. Is this a bug or am I missing something here? Let me know anything I can provide to help identify the issue.

**Comment by chinchang** [comment]
Hi @AdamGaffney96 the game actually considers your score to decide if its a high score or not. So since you got 600 even with your lower count, it was not considered a highscore and kept showing previous one. As for why you keep getting 600 is because there is a certain threshold (~1000 chars) after which you score starts improving beyond 600 (which you get on 100% match).
Hope that clarifies :)
